sonar.projectKey=Onesiforus-Rade-Putra_promtingDBP
sonar.organization=onesiforus-rade-putra

sonar.projectName=promtingDBP
sonar.projectVersion=1.0

sonar.sources=lib
sonar.tests=test

sonar.sourceEncoding=UTF-8
sonar.dart.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/build/**,**/.dart_tool/**,**/android/**,**/ios/**,**/linux/**,**/macos/**,**/windows/**,**/web/**